CREATE DATABASE IF NOT EXISTS libreria;
USE libreria;

DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS libros;

CREATE TABLE usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    CORREO VARCHAR(255) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    CONTRASENA_ORIGINAL VARCHAR(50) NOT NULL
);

CREATE TABLE libros (
	NOMBRE VARCHAR(50) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    PUBLICACION DATE NOT NULL,
    GENERO VARCHAR(20) NOT NULL,
    SINOPSIS VARCHAR(255) NOT NULL
);
