CREATE DATABASE IF NOT EXISTS libreria;
USE libreria;

DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS libros;

CREATE TABLE usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    CORREO VARCHAR(255) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    CONTRASENA_ORIGINAL VARCHAR(50) NOT NULL
);

CREATE TABLE libros (
    NOMBRE VARCHAR(50) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    PUBLICACION DATE NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    SINOPSIS TEXT(355) NOT NULL,
    PORTADA VARCHAR(255)  -- Guardar nombre de imagen en la portada "HarryPotter.jpg"
);

