CREATE DATABASE IF NOT EXISTS usuarios;
USE usuarios;

DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    CORREO VARCHAR(255) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    CONTRASENA_ORIGINAL VARCHAR(50) NOT NULL
);
